image: node:latest
stages:
  - release
  - deploy

publish:
  stage: release
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  
deploy:
  stage: deploy
  before_script:
    - make down || true
    - docker rmi mystore_web || true
    - docker rmi mystore_bot || true
  script:
    - make prod
