stages:
  - prepare
  - test
  - deploy
  - release

default:
  image: node:lts-alpine
  cache: &cache
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
      - ./node_modules
      - apps/web/node_modules
    policy: pull

before_script:
  - npm i -g pnpm
  - pnpm config set store-dir .pnpm-store

install:js:
  stage: prepare
  interruptible: true
  cache:
    <<: *cache
    policy: push
  script:
    - pnpm install --frozen-lockfile

publish:
  stage: release
  script:
    - rm -rf .husky
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - pnpm build
    - pnpm semantic-release
  
deploy_storybook:
  stage: deploy
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider;
    - pnpm storybook:build
    - rm -rf /opt/websites/storybook/*
    - mv -f ./storybook-static/* /opt/websites/storybook

unit_test:
  stage: test
  script:
    - pnpm run test

