default:
  image: node:latest
  before_script:
    - npm i -g pnpm
    - pnpm i

stages:
  - release
  - deploy

publish:
  stage: release
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - pnpm build
    - npm publish
  
deploy_storybook:
  stage: deploy
  script:
    - pnpm storybook:build
    - rm -rf /opt/websites/storybook
    - mkdir /opt/websites/storybook
    - mv -f ./storybook-static/* /opt/websites/storybook
