image: node:latest
stages:
  - release
  - deploy

semantic-release:
  image: node:12
  stage: release
  before_script:
    - pnpm install -g semantic-release @semantic-release/gitlab @semantic-release/exec
    - |
    cat <<-EOF >> .releaserc.yml
      ---
      verifyConditions:
        - "@semantic-release/gitlab"
      prepare: false
      publish:
        - "@semantic-release/gitlab"
      success: false
      fail: false
      npmPublish: false
      plugins:
        - "@semantic-release/commit-analyzer"
        - "@semantic-release/release-notes-generator"
        - "@semantic-release/gitlab"
        - - "@semantic-release/exec"
          - prepareCmd: "set-version ${nextRelease.version}"
            publishCmd: "publish-package"      
    EOF
  script:
    - semantic-release
  only:
    refs:
      - main
      - beta
      - /^\d+.x$/
      - /^\d+.\d+.x$/
  
deploy:
  stage: deploy
  before_script:
    - make down || true
    - docker rmi mystore_web || true
    - docker rmi mystore_bot || true
  script:
    - make prod
