default:
  image: node:latest
  before_script:
    - npm i -g pnpm
    - pnpm i

stages:
  - deploy
  - release

publish:
  stage: release
  script:
    # - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - pnpm build
    - pnpm semantic-release
    # - npm publish
  
deploy_storybook:
  stage: deploy
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider;
    - pnpm storybook:build
    - rm -rf /opt/websites/storybook/*
    - mv -f ./storybook-static/* /opt/websites/storybook
