export enum BaseColor {
  LIGHT = 'var(--color-base-light)',
  NEUTRAL_100 = 'var(--color-base-neutral-100)',
  NEUTRAL_200 = 'var(--color-base-neutral-200)',
  NEUTRAL_300 = 'var(--color-base-neutral-300)',
  NEUTRAL_400 = 'var(--color-base-neutral-400)',
  NEUTRAL_500 = 'var(--color-base-neutral-500)',
  NEUTRAL_600 = 'var(--color-base-neutral-600)',
  NEUTRAL_700 = 'var(--color-base-neutral-700)',
  NEUTRAL_800 = 'var(--color-base-neutral-800)',
  ERROR_LIGHT = 'var(--color-base-error-light)',
  ERROR_DARK = 'var(--color-base-error-dark)',
  ERROR = 'var(--color-base-error)',
  WARNING_LIGHT = 'var(--color-warning-light)',
  WARNING_DARK = 'var(--color-warning-dark)',
  WARNING = 'var(--color-warning)',
  VIOLET_LIGHTER = 'var(--color-violet-lighter)',
  VIOLET_LIGHT = 'var(--color-violet-light)',
  VIOLET = 'var(--color-violet)',
  VIOLET_DARK = 'var(--color-violet-dark)',
}
